name: lanuage
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Core packages
  camera: ^0.10.5+9
  permission_handler: ^11.0.1
  provider: ^6.0.4
  
  # UI packages
  google_fonts: ^6.2.1
  flutter_animate: ^4.1.1+1
  font_awesome_flutter: ^10.1.0
  lottie: ^3.3.1
  
  # ML and Translation packages - Using compatible versions
  google_mlkit_commons: ^0.5.0
  google_mlkit_text_recognition: ^0.9.0
  google_mlkit_language_id: ^0.8.0
  google_mlkit_object_detection: ^0.9.0
  google_mlkit_image_labeling: ^0.8.0
  google_mlkit_translation: ^0.8.0
  translator: ^1.0.3+1
  path_provider: ^2.1.2
  path: ^1.8.3
  image: ^4.1.3
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.10
  go_router: ^15.1.1

  # AR and Vision
  arcore_flutter_plugin:
    git:
      url: https://github.com/giandifra/arcore_flutter_plugin.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/
    - assets/models/